excluded:
- Pods

disabled_rules:
- trailing_whitespace

function_body_length:
- 50
- 100

line_length:
warning: 150

function_parameter_count:
warning: 10
error: 15

file_length:
warning: 500

type_body_length:
warning: 450
error: 450
